---
- name: Check if HANA DB was already installed
  stat:
    path: "/hana/shared/{{ hana_sid | upper }}/exe/linuxx86_64/hdb"
  register: hdb_install_status

- name: Check SAP NW ASCS installation status
  stat:
    path: "/usr/sap/{{ sap_sid | upper }}/ASCS{{ sap_ascs_instance_number }}/exe/sapstartsrv"
  register: ascs_stat_result

- name: Check SAP NW ERS installation status
  stat:
    path: "/usr/sap/{{ sap_sid | upper }}/ERS{{ sap_ers_instance_number }}/exe/sapstartsrv"
  register: ers_stat_result

- name: Reboot target host
  reboot:
    connect_timeout: 5
    post_reboot_delay: 10
  changed_when: False
  when: not hdb_install_status.stat.exists and not ascs_stat_result.stat.exists and not ers_stat_result.stat.exists
...
