---
- hosts: hdb_iphost1,hdb_iphost2
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Import playbook variables
      include_vars: "{{ item }}"
      loop:
        - "saphana-vars.yml"
        - "hainfra-vars.yml"
  roles:
    - hdbpacemakercfg
...
