---
- name: Check SAP NW ASCS installation status
  stat:
    path: "/usr/sap/{{ sap_sid | upper }}/ASCS{{ sap_ascs_instance_number }}/exe/sapstartsrv"
  register: ascs_stat_result

- name: Check SAP NW ERS installation status
  stat:
    path: "/usr/sap/{{ sap_sid | upper }}/ERS{{ sap_ers_instance_number }}/exe/sapstartsrv"
  register: ers_stat_result

- name: Reboot target host
  reboot:
    connect_timeout: 5
    post_reboot_delay: 10
  changed_when: False
  when: not ascs_stat_result.stat.exists and not ers_stat_result.stat.exists
...
